[package]
name = "Dittos"
version = "0.0.1"

[addresses]
dittos = "_"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'zk-hack'
subdir = 'aptos-move/framework/aptos-framework'